[package]
name = "optimization_tools"
version = "0.1.0"
edition = "2021"
authors = [
  "Kostiantyn Wandalen <wandalen@obox.systems>"
]
license = "MIT"
readme = "Readme.md"
documentation = "https://docs.rs/optimization_tools"
repository = "https://github.com/Wandalen/wTools/tree/master/module/core/optimization_tools"
homepage = "https://github.com/Wandalen/wTools/tree/master/module/core/optimization_tools"
description = """
Playground for experimenting with optimization algorithms.
"""
categories = [ "algorithms", "development-tools" ]
keywords = [ "fundamental", "general-purpose" ]

# xxx : qqq : switch that on
# [lints]
# workspace = true

[package.metadata.docs.rs]
features = [ "full" ]

[features]
default = [
  "enabled",
]
full = [
  "enabled",
]
enabled = []
rapidity_6 = [] # to enable slow tests
rapidity_7 = [ "rapidity_6" ] # to enable slow tests
rapidity_8 = [ "rapidity_7" ] # to enable slow tests
rapidity_9 = [ "rapidity_8" ] # to enable slow tests
static_plot = [ "plotters" ]
dynamic_plot = [ "static_plot", "plotters-backend", "piston_window" ]

[dependencies]
derive_tools = { workspace = true, features = ["default"] }
deterministic_rand = { workspace = true, features = [ "default" ] }
iter_tools = { workspace = true, features = [ "default" ] }
meta_tools = { workspace = true, features = [ "meta_constructors" ] }
error_tools = { workspace = true, features = ["default"] }
env_logger = "0.10.1"
log = "0.4.20"
rand = "0.8.5"
statrs = "0.16.0"
nalgebra = "0.32.3"

# blas-src = "0.6"
blas-src = { version = "0.9", features = ["openblas"] }
ndarray = "0.15.6"
ndarray-linalg = { version = "0.16", features = ["openblas"]}
plotters = { version = "0.3.5", optional = true }
plotters-backend = { version = "0.3.5", optional = true }
piston_window = { version = "0.120.0", optional = true }

[dev-dependencies]
test_tools = { workspace = true }
