name : plot_interface

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/move/plot_interface/Cargo.toml'
      module_name : 'plot_interface'
      commit_message : ${{ github.event.head_commit.message }}
