name : w4d

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/blank/w4d/Cargo.toml'
      module_name : 'w4d'
      commit_message : ${{ github.event.head_commit.message }}
