name : fundamental_data_type

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/fundamental_data_type/Cargo.toml'
      module_name : 'fundamental_data_type'
      commit_message : ${{ github.event.head_commit.message }}
