name : std_x

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/alias/std_x/Cargo.toml'
      module_name : 'std_x'
      commit_message : ${{ github.event.head_commit.message }}
