name : willbe_old

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/blank/willbe_old/Cargo.toml'
      module_name : 'willbe_old'
      commit_message : ${{ github.event.head_commit.message }}
