name : for_each

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/for_each/Cargo.toml'
      module_name : 'for_each'
      commit_message : ${{ github.event.head_commit.message }}
