name : interval_adapter

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/interval_adapter/Cargo.toml'
      module_name : 'interval_adapter'
      commit_message : ${{ github.event.head_commit.message }}
