name : clone_dyn_meta

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/clone_dyn_meta/Cargo.toml'
      module_name : 'clone_dyn_meta'
      commit_message : ${{ github.event.head_commit.message }}
