name : strs_tools

on : push

env :
  CARGO_TERM_COLOR : always

jobs :

  test :
    uses : Wandalen/wTools/.github/workflows/StandardRustPush.yml@alpha
    with :
      manifest_path : 'module/core/strs_tools/Cargo.toml'
      module_name : 'strs_tools'
      commit_message : ${{ github.event.head_commit.message }}
